version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test
  deploy-to-staging:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run: npm install surge
      - run: yarn build
      - run:
            name: "Deploy to Staging - Surge"
            command: |
              npx surge --project build --domain ci-ci-practical-staging.surge.sh
  ui-tests:
    docker:
      - image: cimg/node:14.15.4-browsers
    steps:
      - checkout
      - run: yarn e2e



workflows:
  orb-free-workflow:
    jobs:
      - test
      - deploy-to-staging:
         filters:
           branches:
             only: master
      - ui-tests:
          requires:
            - deploy-to-staging

  