version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test
  build:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run:
            name: "echo SURGE_LOGIN"
            command: |
              echo $SURGE_LOGIN
  deploy-to-staging:
    docker:
      - image: cimg/node:14.15.4
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Staging
          command: npx surge build/ https://ci-ci-practical-staging.surge.sh


workflows:
  orb-free-workflow:
    jobs:
      - test
      - build
      - deploy-to-staging:
          filters:
            branches:
              only: master

  